### ISSUE TITLE
Update react-scripts to latest version

### ISSUE THREAD

**Issue by msiadak** [codefordenver/Comrad#259]
## Description of Issue

Currently, the front-end is using react-scripts v1.1.4, which is pretty out of date at this point.  We're also getting pinged by Github for a security vulnerability in an old version webpack-dev-server which is a dependency of react-scripts v1.1.4.

Additionally, upgrading will allow us to use some nice newer tooling seen here:

https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

## Possible Solution and/or Approach

1. `npm install react-scripts@latest`

2. Test the client, at minimum make sure it still runs without throwing errors.

## Approval?

_Leads Comment Below_

**Comment by dzimmerman902** [comment]
Yup! That is on my todo list. I'm running into some issues with the back button feature Sean asked for so that's why I haven't merged my stuff, thought it would be a lot easier than I thought. I'm going to skip that part, get the new code merged and start the update. Didn't want to do it just incase it broke the code.
