### ISSUE TITLE
Redux select input type is returning a json string instead of object

### ISSUE THREAD

**Issue by jberns** [codefordenver/Comrad#492]
## Description of Issue

The current repeat rule is using a basic select component which is returning a json string that is being parsed in the backend.  If we can make the following updates it would help clean up the creation and updating of new shows:
1) Return an object into the store when one of the repeat choices are selected.
2) Add the repeat start and end date into the returned object (currently they are outside of the object as they need to be used elsewhere in the show creation/update process.

## Possible Solution and/or Approach

Potential Solutions:
1) Update the way redux returns the repeat rule object (See RepeatDropdown.js)
2) Change the schema such that the repeat start and repeat end date are not part of the repeat_rule embedded document.

<img width="988" alt="Screen Shot 2019-06-24 at 6 33 03 PM" src="https://user-images.githubusercontent.com/519070/60060599-a815fd00-96ae-11e9-9c51-10e1b0bc4631.png">

https://stackoverflow.com/questions/36915306/does-redux-form-field-value-can-hold-object-instead-of-just-a-string

**Comment by kmid5280** [comment]
I looked into this and am not sure it's possible to post the value as an object. In the above StackOverflow link posted in this issue, there is a suggestion in the discussion that this functionality is not supported in Redux Form v7. In the Redux Form docs I did find some information about posting values as complex values such as arrays and objects ([link here](https://redux-form.com/5.2.3/#/examples/complex?_k=watr7f)), but it doesn't demonstrate how to post values as an object. To me it's inconclusive whether this is possible.

**Comment by seankwilliams** [comment]
Thanks for researching this @kmid5280 ! The link you referenced on Redux Form is using `JSON.stringify` for setting the values of an `option` element, so I think the Redux Form example is probably using `JSON.parse` somewhere just like we are. I'm going to close this issue since it's more a code cleanup thing.

I'll probably make an issue in the future to handle the `JSON.parse` logic on the front-end instead of the back-end. That way, the back-end can receive an object rather than string for `repeat_rule`, which will be what developers would expect to use if they're hitting the API from outside of Comrad.
