### ISSUE TITLE
Calendar form should close when area outside form is clicked

### ISSUE THREAD

**Issue by kmid5280** [codefordenver/Comrad#524]
## Description of Issue

Form that pops up when spot on calendar is clicked does not close when an area outside the form is clicked.

## Possible Solution and/or Approach
Could solve using a ref and event listener similar to the Dropdown component. [https://github.com/codefordenver/Comrad/blob/development/client/src/components/Dropdown/Dropdown.js](url)

**Comment by jberns** [comment]
This was intentional at the time I made this because someone may be writing a lot of show data I didn't want them to accidentally click outside of the modal and then all that data is lost when it is closed so they have to use the 'CANCEL' button. 

@seankwilliams Can you provide any additional info on what the expected 'close' functionality should be for the new show and edit show forms?

**Comment by dzimmerman902** [comment]
I agree with @jberns

**Comment by kmid5280** [comment]
@jberns @dzimmerman902 Got it, that makes sense.

**Comment by seankwilliams** [comment]
@kmid5280 thanks for pointing this out!

@dzimmerman902 and @jberns - I think we can leave the current behavior as is (clicking the modal background does NOT close the modal). Eventually we might want to let users close that modal by clicking the background and prompt them with a confirmation alert if they've entered information in the form that would be erased. I'd say that's more of a v2 thing though.
