### ISSUE TITLE
Adding new giveaway in traffic page without specifying event name causes error

### ISSUE THREAD

**Issue by kmid5280** [codefordenver/Comrad#712]
## Description of Issue

If you add a new Giveaway in the traffic page and don't specify an event name, then the page will return an error when you attempt to view the time slow that the Giveaway is in in Show Builder.

To replicate:
1. Go to the Traffic page.
2. Click Add.
3. Select 'Giveaway' from the Type dropdown menu.
4. Create a new Giveaway without specifying an event name.
5. Go to Show Builder.
6. Click on the time slot where the Giveaway will appear in the scratchpad. This will return an error, and you will not be able to see any of the information for that time slot.

## Possible Solution and/or Approach

Make the Event Name a required field, or replace with 'undefined' if no entry is given.

## Additional Comments

_Comments Go Here_

**Comment by seankwilliams** [comment]
@kmid5280 Thank you for creating the issue for this! I think the best solution for this would actually be to Show Builder to change where it's checking for `giveaway_details` and handle a case where `giveaway_details` is undefined.

**Comment by kmid5280** [comment]
@seankwilliams Would it be possible to utilize an approach in which we include a conditional within the encodeURIComponent sections in client/src/components/ShowBuilderItemList/ShowBuilderItemList.js that will check for the existence of these specific values? For instance, changing this:
`'?venue=' +
   encodeURIComponent(traffic.traffic_details.giveaway_details.venue
 ) +`

to this:

`'?venue=' +
                      encodeURIComponent(
                        traffic.traffic_details.giveaway_details.venue != 'undefined'
                          ? traffic.traffic_details.giveaway_details.venue
                          : 'undefined'
                      ) +`

**Comment by seankwilliams** [comment]
@kmid5280 Yes, that's a great approach! Rather than `traffic.traffic_details.giveaway_details.venue != 'undefined'`, I think you may need to do `traffic.traffic_details.giveaway_details != null && traffic.traffic_details.giveaway_details.venue != null`. That way, you cover if `giveaway_details` is null or undefined and if `giveaway_details.venue` is. Then, if it is undefined, I would write a blank string to the value of `venue` in the URL rather than writing `undefined`. The DJ entering the winner information won't know what "undefined" is if they see that in the venue field in Jotform.

**Comment by kmid5280** [comment]
@seankwilliams This approach didn't quite work so well, and I'm wondering if we've correctly identified the point of failure. It looks as if the page attempts to render the "description" property regardless of whether or not it exists (which it will not if certain fields are not entered in the creation of the Giveaway item). Where in the process does this part happen exactly? It's a bit hard to pinpoint.

**Comment by seankwilliams** [comment]
@kmid5280 I'm not sure what issue you were running into with the "description" property but here are some more details that will hopefully help. Show Builder will always be viewed after the giveaway event has already been created. The different fields like `giveaway_details.venue` and `giveaway_details.event_name` would usually be entered by the time someone views Show Builder, but those fields shouldn't be required on the traffic form because there may be giveaways that don't necessarily match the fields available for giveaway_details. The fields that are there right now are pretty specific for concerts, but the event could be used by stations for other types of giveaways.

Did you run into problems with `traffic.traffic_details.description` not being set?

And then, if you were running into issues with the code getting messy when checking for `traffic.traffic_details.giveaway_details != null && traffic.traffic_details.giveaway_details.venue != null`, I'd suggest making a function that could handle some of these checks. It could be called `getGiveawayDetailsProperty`, and it could check for whether `giveaway_details` is set, and return a blank string if it isn't. If it is set, it would return the value of the property name passed to the function (like `venue`), or a blank string if it doesn't exist.

**Comment by kmid5280** [comment]
> Did you run into problems with `traffic.traffic_details.description` not being set?

If I understand the question right, this is basically the issue. If I create a new giveaway event and don't enter values for some fields, then it will not create a "description" property at all for that giveaway and `traffic.traffic_details.description` ends up being undefined. This causes an error when clicking on the show in Show Builder which contains that specific giveaway. I've attached a screenshot that shows the error.
<img width="511" alt="trafficdetails" src="https://user-images.githubusercontent.com/35879775/115807457-e31a1200-a3a5-11eb-8cd6-2f653294c047.png">

**Comment by seankwilliams** [comment]
@kmid5280 Got it! In that case, to fix this issue, we'll have to properly check that traffic.trafic_details.description is present.

To fix this, can you replace line 174 of client\src\components\ShowBuilderItemList\ShowBuilderItemList.js with:
{traffic.traffic_details.description != null && traffic.traffic_details.description

And then, line 183 should be replaced with:
{typeof traffic.traffic_details.description === 'undefined' || traffic.traffic_details.description

**Comment by kmid5280** [comment]
@seankwilliams I implemented these changes and pushed a commit to a new branch. I also added another conditional on line 44 to check for the existence of traffic.traffic.details.giveaway_details. The new code seems to work so far but I also want to make sure it is populating all of the fields correctly when rendering an item that doesn't have the description or giveaway_details properties.

Is there a reason to use `typeof traffic.traffic_details.description === 'undefined'` versus `traffic.traffic_details.description != null`? Both approaches appeared to work both on line 44 and line 185.

**Comment by seankwilliams** [comment]
@kmid5280 That's looking good!! No reason to use `typeof traffic.traffic_details.description === 'undefined'` versus `traffic.traffic_details.description != null`. There is a difference between checking for typeof undefined vs. null (https://stackoverflow.com/questions/5101948/javascript-checking-for-null-vs-undefined-and-difference-between-and), but it won't affect the execution of the code here.
